config/routes.rb
SimpleTicket::Application.routes.draw do
  devise_for :users

  resources :categories

  resources :users

  resources :tickets
  
  root :to => 'tickets#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tickets
  validates_presence_of :name
  validates_uniqueness_of :name
  
  def is_associated?
    tickets.count > 0
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :ticket_status
  validates_presence_of :title, :description, :user_id, :category_id, :ticket_status_id
    
end

app/models/ticket_status.rb
class TicketStatus < ActiveRecord::Base
  has_many :tickets
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tickets

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :is_admin
  
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :password, :on => :create
  validates :password, :confirmation => true
  
  def is_associated?
    tickets.count > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.includes(:tickets).order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    
    if @category.is_associated?
      redirect_to categories_url, alert: "Category not deleted because associated to a ticket."
    else
      @category.destroy
      redirect_to categories_url, notice: "Category successfully deleted."
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user!, :only => :delete
  
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.includes(:category, :user, :ticket_status)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new
    @ticket.ticket_status = TicketStatus.find_by_name("Open")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:tickets).order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.is_admin = User.count == 0

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])

    if @user.is_admin
      redirect_to users_path, alert: 'Cannot delete admin.'
    else
      if @user.is_associated?
        redirect_to users_path, alert: 'Cannot delete user because associated to a ticket.'
      else
        @user.destroy
        redirect_to users_url, notice: 'User was successfully deleted.'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_icon_link_to (text, url, icon, html_options = {})
    link_to url, html_options do
      "<i class=\"#{icon}\"></i> #{text}".html_safe
    end
  end
  
  def bootstrap_dropdown_button text, icon, links
    link_items = ""
    links.each do |l|
      link_items += "<li>#{l}</li>" 
    end
    "
      <div class=\"btn-group\">
        <a class=\"btn dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">
          <i class=\"#{icon}\"></i> #{text}
          <span class=\"caret\"></span>
        </a>
        <ul class=\"dropdown-menu\">#{link_items}</ul>
      </div>
    ".html_safe
  end
  
  def show_flash
    f = ""
    f += "<div class=\"alert alert-success\">#{notice}</div>" if notice
    f += "<div class=\"alert alert-error\">#{alert}</div>" if alert
    f.html_safe
  end
  
  def ticket_status_label status
    label = case status
      when "Open"
        "important"
      when "Closed"
        "success"
      end
    "<span class=\"label label-#{label}\">#{status}</span>".html_safe
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-error">
      <b><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</b>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-actions">
    <%= f.submit :class => "btn btn-success" %><br />
    <%= link_to 'Cancel', categories_path %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="page-header"><h1>Edit category</h1></div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="page-header">
  <h1>
    List of categories
    <%= bootstrap_icon_link_to 'New Category', new_category_path, "icon-plus icon-white", :class => "btn btn-success" %>
  </h1>
</div>

<%= show_flash %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Name</th>
    <th>Tickets</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.tickets.count %></td>
    <td>
      <%= bootstrap_icon_link_to 'Edit', edit_category_path(category), "icon-pencil icon-white", :class => "btn btn-small btn-primary" %>
      <%= bootstrap_icon_link_to 'Delete', category, "icon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "btn btn-small btn-danger" %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

app/views/categories/new.html.erb
<div class="page-header"><h1>New category</h1></div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SimpleTicket</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "SimpleTicket", root_url, :class => "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to 'Tickets', tickets_path %></li>
                 <% if user_signed_in? %>   
                    <li><%= link_to 'Categories', categories_path %></li>
                    <li><%= link_to 'Users', users_path %></li>
                    <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
                  <% else %>
                    <li><%= link_to "Log In", new_user_session_path %></li>
                  <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
            <%= yield %>
            </div>
            <div class="span1">&nbsp;</div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Information</h3>
                <p>
                  Simple Ticket is an easy to use ticket reporting appliction. Add a ticket by clicking on the <b><em>New Ticket</em></b> button. Fill in <b>all</b> the fields in the form. You can edit the content of a ticket by opening the ticket and clicking on the <b><em>Edit</em></b> button. If you have any questions ask Guillaume:
                </p>
                 <ul class="nav nav-list">
                   <li><%= bootstrap_icon_link_to "gdf@tdh.ch", "mailto:gdf@tdh.ch", "icon-envelope" %></li>
                   <li><i class="icon-info-sign"></i> +961 76 13 39 40</li>
                </ul>
            </div>
           </div>
          </div>
        </div>

      <footer>
        <p>&copy; Guillaume Deflaux</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div class="alert alert-error">
      <b><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</b>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id, "Feedback by" %>
    <%= f.select :user_id, User.order("name ASC").map { |c| [c.name, c.id] }, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :category_id %>
    <%= f.select :category_id, Category.order("name ASC").map { |c| [c.name, c.id] }, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :ticket_status_id %>
    <%= f.select :ticket_status_id, TicketStatus.order("position ASC").map { |c| [c.name, c.id] }, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "span5" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "span5" %>
  </div>
  <div class="form-actions">
    <%= f.submit :class => "btn btn-success" %><br />
    <% if @ticket.id %>
      <%= link_to 'Cancel', @ticket, :class => "btn" %>
    <% else %>
      <%= link_to 'Cancel', tickets_path %>
    <% end %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<div class="page-header"><h1>Edit ticket</h1></div>

<%= render 'form' %>

app/views/tickets/index.html.erb
<div class="page-header">
  <h1>
    List of tickets
    <%= bootstrap_icon_link_to 'New Ticket', new_ticket_path, "icon-plus icon-white", :class => "btn btn-success" %>
  </h1>
</div>

<%= show_flash %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Status</th>  
    <th>Category</th>
    <th>Title</th>
    <th>Feedback by</th>
  </tr>
  </thead>
  <tbody>
<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket_status_label ticket.ticket_status.name %></td>
    <td><%= ticket.category.name %></td>
    <td><%= link_to ticket.title, ticket %></td>
    <td><%= ticket.user.name %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/tickets/new.html.erb
<div class="page-header"><h1>New ticket</h1></div>

<%= render 'form' %>

app/views/tickets/show.html.erb
<div class="page-header">
  <h1>
    Ticket Details
    <% if user_signed_in? and current_user.is_admin %>
      <%= bootstrap_icon_link_to 'Delete', @ticket, "icon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger" %>
    <% end %>
      <%= bootstrap_icon_link_to 'Edit', edit_ticket_path(@ticket), "icon-pencil icon-white", :class => "btn btn-primary" %>
  </h1>
</div>

<table class="table table-striped table-bordered table-condensed">
  <tbody>
    <tr>
      <td class="top"><b>Status:</b></td>
      <td><%= ticket_status_label @ticket.ticket_status.name %></td>
    </tr>
    <tr>
      <td class="top"><b>Category:</b></td>
      <td><%= @ticket.category.name %></td>
    </tr>
    <tr>
      <td class="top"><b>Feedback by:</b></td>
      <td><%= @ticket.user.name %></td>
    </tr>
    <tr>
      <td class="top"><b>Title:</b></td>
      <td><%= @ticket.title %></td>
    </tr>
    <tr>
      <td class="top"><b>Description:</b></td>
      <td><%= RedCloth.new(@ticket.description).to_html.html_safe %></td>
    </tr>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <b><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</b>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-actions">
    <%= f.submit :class => "btn btn-success" %><br />
    <%= link_to 'Cancel', users_path %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="page-header"><h1>Edit user</h1></div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>
    List of users
    <%= bootstrap_icon_link_to 'New User', new_user_path, "icon-plus icon-white", :class => "btn btn-success" %>
  </h1>
</div>

<%= show_flash %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Tickets</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @users.each do |user| %>
  <tr>
    <td>
      <%= user.name %>
      <% if user.is_admin %>
        <span class="label label-info">Admin</span>
      <% end %>
    </td>
    <td><%= user.email %></td>
    <td><%= user.tickets.count %></td>
    <td>
      <%= bootstrap_icon_link_to "Edit", edit_user_path(user), "icon-pencil icon-white", :class => "btn btn-small btn-primary" %>
      <%= bootstrap_icon_link_to 'Delete', user, "icon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "btn btn-small btn-danger" %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

app/views/users/new.html.erb
<div class="page-header"><h1>New user</h1></div>

<%= render 'form' %>